---
theme: dark
jwt_secret: "{{ authelia.secret }}"
default_redirection_url: "{{ authelia.redirect }}"
server:
  host: 0.0.0.0
  port: 9080
  path: ""
  read_buffer_size: 4096
  write_buffer_size: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""
log:
  level: debug
authentication_backend:
  disable_reset_password: false
  refresh_interval: 5m
  file: 
    path: /config/users_db.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 512
      parallelism: 8
access_control:
  default_policy: deny
  networks:
    - name: internal
      networks:
        - 172.22.0.0/16
        - 192.168.1.0/24
  rules:
    - domain: '*."{{ domain }}"'
      policy: one_factor
      networks:
        - internal
        - 192.168.1.0/24
        - 172.22.0.0/16
session:
  name: authelia_session
  domain: "{{ domain }}"
  same_site: lax
  secret: "{{ authelia.password }}"
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  redis:
    host: "{{ redis.ip}}"
    port: "{{ redis.port }}"
    password: "{{ redis.password }}"
    database_index: 0
    maximum_active_connections: 8
    minimum_idle_connections: 0
regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 5m
storage:
  encryption_key: "{{ authelia.encryption_key }}"
  local:
    path: /config/db.sqlite3

notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/notification.txt
  #  disable_startup_check: false
  #  smtp:
  #    host: 127.0.0.1
  #    port: 1025
  #    timeout: 5s
  #    username: test
  #    password: password
  #    sender: "Authelia <admin@example.com>"
  #    identifier: localhost
  #    subject: "[Authelia] {title}"
  #    startup_check_address: test@authelia.com
  #    disable_require_tls: false
  #    disable_html_emails: false
  #    tls:
  #      skip_verify: false
  #      minimum_version: TLS1.2
      #mysql:
      #  host: 172.22.0.6
      #  port: 3306
      #  database: authelia
      #  username: authelia
      #  password: 
      #  timeout: 5s
      #  ldap:
      #    implementation: custom
      #    url: ldap://127.0.0.1
      #    timeout: 5s
      #    start_tls: false
      #    tls:
      #      skip_verify: false
      #      minimum_version: TLS1.2
      #    base_dn: dc=example,dc=com
      #    additional_users_dn: ou=users
      #    users_filter: (&({username_attribute}={input})(objectClass=person))
      #    additional_groups_dn: ou=groups
      #    groups_filter: (&(member={dn})(objectClass=groupOfNames))
      #    user: cn=admin,dc=example,dc=com
      #    password: "{{ authelia.password }}" 
      #totp:
      #  issuer: authelia.com
      #  algorithm: sha1
      #  digits: 6
      #  period: 30
      #  skew: 1
      #duo_api:
      #  hostname: api-123456789.example.com
      #  integration_key: ABCDEF
      #  secret_key: 1234567890abcdefghifjkl
      #  enable_self_enrollment: false
      #ntp:
      #  address: "time.cloudflare.com:123"
      #  version: 4
      #  max_desync: 3s
      #  disable_startup_check: false
      #  disable_failure: false
      #
