- name: Update Debian
  become: yes
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Install Packages
  become: yes
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install Packages
  become: yes
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'alpine'
