---
- name: Setup all devices
  hosts: all:!uni
  gather_subset: min
  strategy: free
  vars_files:
    - secrets.yml
  tasks:
    - name: Setup Devices
      include_role:
        name: setup

          #- name: Setup my devices
          #  hosts: all:!oracle
          #  gather_subset: min
          #  vars_files:
          #    - secrets.yml
          #  tasks:
          #    - name: Setup Devices
          #      include_role:
          #        name: home

- name: Unraid
  hosts: unraid
  gather_subset: min
  strategy: free
  vars_files:
    - secrets.yml
  tasks:
    - name: Setup Unraid
      include_role:
        name: unraid

- name: Setup oracle devices
  hosts: oracle
  gather_subset: min
  strategy: free
  vars_files:
    - secrets.yml
  tasks:
    - name: Setup Oracle specifics
      include_role:
        name: oracle
