- name: Update
  async: 60
  poll: 0
  ansible.builtin.apt:
    update_cache: yes
    state: present
    pkg:
      - apt-transport-https
      - curl
      - python3
      - python3-pip
      - ca-certificates
      - gnupg
      - lsb-release
      - ipvsadm
   
- name: Install Packages
  async: 60
  poll: 0
  ansible.builtin.apt:
    update_cache: yes
    state: present
    pkg:
      - crun
      - podman
      - python3-pip

- name: Install Python3 client for Kubernetes
  ansible.builtin.pip:
    name: "{{ item }}"
  loop:
    - podman-compose

      #- name: Probe kernel modules
      #  async: 60
      #  poll: 0
      #  ansible.builtin.modprobe:
      #    name: "{{ item }}"
      #    state: present
      #  loop:
      #    - br_netfilter
      #    - overlay
      #
      #- name: Set Kernel Params
      #  async: 60
      #  poll: 0
      #  ansible.posix.sysctl:
      #    name: "{{ item }}" 
      #    value: '1'
      #    sysctl_set: yes
      #  loop:
      #    - net.ipv4.ip_forward
      #    - net.bridge.bridge-nf-call-iptables
      #    - net.bridge.bridge-nf-call-ip6tables
      #
      #- name: Enable Systemd cgroup driver
      #  async: 60
      #  poll: 0
      #  ansible.builtin.blockinfile:
      #    path: /etc/containerd/config.toml
      #    marker: "## {mark} ANSIBLE MANAGED BLOCK ##"
      #    block: |
      #      [plugins."io.containerd.grpc.v1.cri"]
      #        systemd_cgroup = true

      #- name: Enabled plugin in containerd config
      #  async: 60
      #  poll: 0
      #  ansible.builtin.lineinfile:
      #    path: /etc/containerd/config.toml
      #    regexp: ^disabled_plugins = \["cri"]$
      #    line: "# disabled_plugins = [\"cri\"]"

- name: iptables Rule
  ansible.builtin.iptables:
    state: absent
    jump: REJECT
    chain: INPUT
    reject_with: icmp-host-prohibited
  become: yes

- name: iptables Rule
  ansible.builtin.iptables:
    state: absent
    jump: REJECT
    chain: FORWARD
    reject_with: icmp-host-prohibited
  become: yes

- name: Start services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - podman.socket
