- name: init cluster
  shell: kubeadm init --pod-network-cidr="{{ kube_cidr }}" >> cluster_init.txt
  args:
    chdir: $HOME
    creates: cluster_init.txt

- name: create .kube directory
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes
    owner: $USER
