- name: Start with docker-compose
  community.docker.docker_compose:
    docker_host: unix://var/run/podman/podman.sock
    project_name: ludwig
    definition: "{{ lookup('template', 'ludwig-compose.yml') | from_yaml }}"
