- name: Setup Timezone
  community.general.timezone:
    name: Europe/London

- name: Install Packages
  ansible.builtin.apt:
    name:
      - python3
      - python3-dev
      - python3-pip 
      - python3-venv
      - podman
      - sudo
    update_cache: yes

- name: Start services
  import_tasks: systemd.yml
