version: '3.9'
services:

  prometheus:
    image: docker.io/prom/prometheus:latest    
    container_name: prometheus
    restart: unless-stopped
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/usr/share/prometheus/console_libraries
    - --web.console.templates=/usr/share/prometheus/consoles
    networks:
      pod-net:
        ipv4_address: 172.22.0.91
    ports:
      - 9090:9090
    volumes:
      - "/mnt/user/appdata/prometheus/etc:/etc"

  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - "GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource"
    networks:
      pod-net:
        ipv4_address: 172.22.0.30
    ports:
      - 3000:3000
    volumes:
      - "/mnt/user/appdata/grafana:/etc/grafana"
      - grafana-volume:/var/lib/grafana

volumes:
    grafana-volume:
        external: false

networks:
  pod-net:
    name: podnet
