version: '3.9'
services:
  traefik:
    image: traefik:2.5
    container_name: traefik
    command:
      - --api=true
      - --api.dashboard=true
      - --api.insecure=true
      - --global.sendanonymoususage=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certresolver=njalla
      - "--entrypoints.websecure.http.tls.domains[0].main=alcock.dev"
      - --certificatesresolvers.njalla.acme.email=paul@alcock.dev
      - --certificatesresolvers.njalla.acme.dnschallenge.provider=njalla
      - --certificatesresolvers.njalla.acme.dnschallenge.delaybeforecheck=30
      - --certificatesresolvers.njalla.acme.storage=/etc/traefik/acme.json
      - --providers.docker.watch=true
      - --providers.docker.exposedbydefault=false
        #      - --entrypoints.metrics.address=9100/tcp
        #      - --entrypoints.traefik.address=9000/tcp
        #- "--entrypoints.websecure.http.tls.domains[0].sans=ludwig.alcock.dev,libreddit.alcock.dev"
    environment:
      - "NJALLA_TOKEN=fbdcd28c0cc197a0dba2a136dd708f31d2c97d73" 
    labels:
      traefik.enable: true
      traefik.http.routers.api.entrypoints: web
      traefik.http.routers.api.service: api@internal
    restart: unless-stopped
    networks:
      pod-net:
        ipv4_address: 172.22.0.43
    ports:
      - 44301:443
      - 8001:80
      - 8183:8080
    volumes:
      - "/mnt/user/appdata/traefik:/etc/traefik:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  pod-net:
    name: podnet
