film_path: "{{ media_path }}/film"
tv_path: "{{ media_path }}/tv"
music_path: "{{ media_path }}/music"
download_path: "{{ media_path }}/downloads"
book_path: "{{ media_path }}/books"

njalla_token: fbdcd28c0cc197a0dba2a136dd708f31d2c97d73
become_pass: Giganthor4125

domain: alcock.dev
update: no
br_name: podnet

tdarr:
  state: present

traefik:
  securename: websecure
  resolver: njalla

authelia:
  encryption_key: lIcmrJq<sSgzk>e6%#5h`%]t
  password: 4d7b8e262ea9c8c9d863
  mysql: 4d7b8e262ea9c8c9d863
  secret: lIcmrJq<sSgzk>e6%#5h`%]t
  redirect: https://video.alcock.dev
  argon_pass: $argon2id$v=19$m=65536,t=1,p=8$bnZidTVadWxlc2xpOHdIUg$l69DQf8+xLLJa4qQEOGOZ6O7FN2cwyBhjoVQT4DQuI8

redis:
  ip: 172.22.0.19
  port: 6379
  password: 4d7b8e262e

mariadb:
  password: 4d7b8e262e
