---
kube_state: "{{ kube_state | default('present') }}"
kube_api: 10.0.10.223
kube_cidr: 12.0.0.0/16
control_endpoint: 10.0.10.223
control_endpoint_port: 6443
cert_key: a145a0f29bb0f073ffa3d224c38abd295d2b6245cd2258fdd045a6095ffd6e40
token: gefv7q.d6gaw4wzlf54rtbj
api_cert_addr: null
kube_config: "{{ ansible_facts['user_dir'] }}/.kube/config"
