#- name: Install Tigera
#  kubernetes.core.k8s:
#    kubeconfig: "{{ kube_config }}/config"
#    state: present
#    definition: "{{ lookup('file', 'tigera-operator.yaml') | from_yaml_all | list }}"
#
#- name: Install Calico
#  kubernetes.core.k8s:
#    kubeconfig: "{{ kube_config }}/config"
#    state: present
#    definition: "{{ lookup('file', 'calico-resources.yaml') | from_yaml_all | list }}"
      #- name: Edit Calico Resources
      #  ansible.builtin.replace:
      #    path: /tmp/calico-resources.yaml
      #    regexp: 'cidr: (\b25[0-5]|\b2[0-4][0-9]|\b[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}\/?[0-9]?[0-9]?'
      #    replace: 'cidr: 12.0.0.0/16'

- name: Get Flannel YAML
  ansible.builtin.get_url:
    url: https://github.com/flannel-io/flannel/raw/master/Documentation/kube-flannel.yml    
    dest: /tmp/kube-flannel.yaml

      #- name: Install Flannel RBAC
      #  ansible.builtin.get_url:
      #    url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel-rbac.yml
      #    dest: /tmp/kube-flannel-rbac.yaml

- name: Create Binary Folder
  ansible.builtin.file:
    path: /opt/bin
    owner: ubuntu
    group: ubuntu
    mode: u=rwx,g=rx,o=rx
    state: directory

- name: Move Flannel Binary
  ansible.builtin.get_url:
    url: https://github.com/flannel-io/flannel/releases/download/v0.17.0/flanneld-amd64
    dest: /opt/bin/flanneld
    mode: +x

- name: Edit Flannel Manifest
  ansible.builtin.replace:
    path: /tmp/kube-flannel.yaml
    regexp: '"Network": "(\b25[0-5]|\b2[0-4][0-9]|\b[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}\/?[0-9]?[0-9]?"'
    replace: '"Network": "12.0.0.0/16"'

      #- name: Deploy Flannel RBAC
      #  kubernetes.core.k8s:
      #    kubeconfig: "{{ kube_config }}/config"
      #    state: present
      #    src: /tmp/kube-flannel-rbac.yaml

- name: Deploy Flannel
  kubernetes.core.k8s:
    kubeconfig: "{{ kube_config }}"
    state: present
    src: /tmp/kube-flannel.yaml
