apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: authelia
  namespace: "{{ oracle_namespace }}"

spec:
  forwardauth:
    address: "https://auth.{{ domain_name }}/api/verify?rd=https://login.example.com"
    trustForwardHeader: true
    authResponseHeaders: 
      - Remote-User
      - Remote-Groups
      - Remote-Name
      - Remote-Email
