apiVersion: v1
kind: Namespace
metadata:
  name: oracle-default
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd

    #---
    #apiVersion: v1
    #kind: PersistentVolume
    #metadata:
    #  name: traefik-pv
    #  namespace: oracle-default
    #  labels:
    #    type: local
    #spec:
    #  storageClassName: fast
    #  capacity:
    #    storage: 20Gi
    #  accessModes:
    #    - ReadWriteMany
    #  hostPath:
    #    path: /home/ubuntu/kubernetes/traefik
    #    type: Directory
    #---
    #apiVersion: v1
    #kind: PersistentVolumeClaim
    #metadata:
    #  name: traefik-pv-claim
    #  namespace: oracle-default
    #spec:
    #  storageClassName: manual
    #  accessModes:
    #    - ReadWriteMany
    #  resources:
    #    requests:
    #      storage: 1Gi
