apiVersion: v1
kind: Namespace
metadata:
  name: oracle-default
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: oracle-pv
  namespace: oracle-default
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/ubuntu/kubernetes/volumes/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-pv-claim
  namespace: oracle-default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

