apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-pv
  namespace: "{{ oracle_namespace }}"
  labels:
    type: local
spec:
  storageClassName: fast
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "{{ config_path }}/traefik"
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-pvc
  namespace: "{{ oracle_namespace }}"
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
