apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-pv-claim
  namespace: oracle-default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
